[user]
name = "Jesse Pai"
email = "jessepai@google.com"

[ui]
editor = "nvim"

[templates]
commit_trailers = '''
if(self.parents().any(|x| x.trailers().contains_key("Change-Id")) &&
  !trailers.contains_key("Change-Id"),
  format_gerrit_change_id_trailer(self)
)
'''

[snapshot]
max-new-file-size = 13984600
